### ISSUE TITLE
Update Ruby Version

### ISSUE THREAD

**Issue by ebertti** [donnex/docker-assets#1] opened 2016-05-22 14:03 UTC
```
DEPRECATION WARNING:
3.5 will no longer support Ruby 1.9.3.
Please upgrade to Ruby 2.0.0 or greater as soon as possible.
```

**Comment by donnex** [comment] 2016-05-22 21:54
Thanks, I just made a small update to the assets containers. Ruby was switched to version 2.3 installed from https://www.brightbox.com/docs/ruby/ubuntu/#Installingthepackages.

Since I'm not using this container often nowadays and I'm not really a ruby person I don't know if this is the best solution.

Docker Hub should pick up on the changes soon and rebuild a new image.

Feel free to try it out and get back to me if if works as intended.

**Comment by donnex** [comment] 2016-05-23 07:58
I just tried the new assets container with updated Ruby and as far as I can tell it's working just as before.

**Comment by ebertti** [comment] 2016-05-23 16:49
Great! Thank you!

**Comment by donnex** [comment] 2016-05-30 09:51
I'm closing the issue now, feel free to open a new one if there's any more problems in the future.

**Closed as completed by donnex** 2016-05-30 09:51 UTC
